<?php
declare(strict_types=1);

// JokeDelivery SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

JokeDeliveryUtility::setRegistrar(function (JokeDeliveryUtility $u): void {
    $u->clean = [JokeDeliveryClean::class, 'call'];
    $u->done = [JokeDeliveryDone::class, 'call'];
    $u->make_error = [JokeDeliveryMakeError::class, 'call'];
    $u->feature_add = [JokeDeliveryFeatureAdd::class, 'call'];
    $u->feature_hook = [JokeDeliveryFeatureHook::class, 'call'];
    $u->feature_init = [JokeDeliveryFeatureInit::class, 'call'];
    $u->fetcher = [JokeDeliveryFetcher::class, 'call'];
    $u->make_fetch_def = [JokeDeliveryMakeFetchDef::class, 'call'];
    $u->make_context = [JokeDeliveryMakeContext::class, 'call'];
    $u->make_options = [JokeDeliveryMakeOptions::class, 'call'];
    $u->make_request = [JokeDeliveryMakeRequest::class, 'call'];
    $u->make_response = [JokeDeliveryMakeResponse::class, 'call'];
    $u->make_result = [JokeDeliveryMakeResult::class, 'call'];
    $u->make_point = [JokeDeliveryMakePoint::class, 'call'];
    $u->make_spec = [JokeDeliveryMakeSpec::class, 'call'];
    $u->make_url = [JokeDeliveryMakeUrl::class, 'call'];
    $u->param = [JokeDeliveryParam::class, 'call'];
    $u->prepare_auth = [JokeDeliveryPrepareAuth::class, 'call'];
    $u->prepare_body = [JokeDeliveryPrepareBody::class, 'call'];
    $u->prepare_headers = [JokeDeliveryPrepareHeaders::class, 'call'];
    $u->prepare_method = [JokeDeliveryPrepareMethod::class, 'call'];
    $u->prepare_params = [JokeDeliveryPrepareParams::class, 'call'];
    $u->prepare_path = [JokeDeliveryPreparePath::class, 'call'];
    $u->prepare_query = [JokeDeliveryPrepareQuery::class, 'call'];
    $u->graphql_body = [JokeDeliveryGraphql::class, 'body'];
    $u->graphql_errors = [JokeDeliveryGraphql::class, 'errors'];
    $u->result_basic = [JokeDeliveryResultBasic::class, 'call'];
    $u->result_body = [JokeDeliveryResultBody::class, 'call'];
    $u->result_headers = [JokeDeliveryResultHeaders::class, 'call'];
    $u->transform_request = [JokeDeliveryTransformRequest::class, 'call'];
    $u->transform_response = [JokeDeliveryTransformResponse::class, 'call'];
});
